type User {
    id: ID!
    fullname: String
    email: String
    phone: String
    products: [Product]
}


type Category {
    id: ID!
    name: String
    images: String
    products: [Product]
}


type Product {
    id: ID!
    title: String
    price: Float
    desc: String
    category: Category
    users: [User]
}


type Query {
	productByCategory(categoryId: ID!): [Product]
    getAllProductsSortedByPrice: [Product]
    getUserById(id: ID!): User
    getCategoryById(id: ID!): Category
    getAllProductsSortedByPrice():[Product]
}

